<?php
declare(strict_types=1);
require __DIR__ . '/config.php';
if(PHP_SAPI!=='cli'){http_response_code(403);exit('CLI access only.');}
$options=getopt('',['file:','confirm','isolated-target:','help']);
if(isset($options['help'])){echo "Usage: php restore.php --file=PATH.sql --isolated-target=DB_NAME --confirm\nThe target name must exactly match POS_DB_NAME. Restore is intentionally refused without the isolated-target assertion.\n";exit(0);}
$backupPath=(string)($options['file']??'');$confirmed=array_key_exists('confirm',$options);$isolated=(string)($options['isolated-target']??'');
if(!$confirmed||$backupPath===''||$isolated!==DB_NAME){fwrite(STDERR,"Refusing restore. Use --file=... --isolated-target=".DB_NAME." --confirm only for an isolated/staging target.\n");exit(2);}if(APP_ENV==='production'){fwrite(STDERR,"Refusing restore while POS_APP_ENV=production. Use an isolated local/staging environment.\n");exit(2);}
$resolved=realpath($backupPath);if($resolved===false||!is_file($resolved)||strtolower(pathinfo($resolved,PATHINFO_EXTENSION))!=='sql'){fwrite(STDERR,"A valid SQL file is required.\n");exit(2);} $actual=hash_file('sha256',$resolved);$checksumFile=$resolved.'.sha256';if(!is_file($checksumFile)){fwrite(STDERR,"Refusing restore without .sha256 companion.\n");exit(1);} $expected=strtolower(strtok(trim((string)file_get_contents($checksumFile))," \t"));if(!hash_equals($expected,$actual)){fwrite(STDERR,"Backup checksum verification failed.\n");exit(1);}
$base=substr($resolved,0,-4);$manifestPath=$base.'.manifest.json';if(!is_file($manifestPath)){fwrite(STDERR,"Refusing restore without Phase-02 backup manifest.\n");exit(1);} $manifest=json_decode((string)file_get_contents($manifestPath),true);if(!is_array($manifest)||($manifest['format']??'')!=='cloud-core-pos-backup-v2'||($manifest['sql']['sha256']??'')!==$actual){fwrite(STDERR,"Backup manifest validation failed.\n");exit(1);} $assetDir=dirname($resolved).DIRECTORY_SEPARATOR.($manifest['uploads']['directory']??'');$expectedFiles=(int)($manifest['uploads']['files']??0);if($expectedFiles>0&&!is_dir($assetDir)){fwrite(STDERR,"Uploads snapshot referenced by manifest is missing.\n");exit(1);}
echo "Creating safety backup before restore...\n";passthru(escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.DIRECTORY_SEPARATOR.'backup.php'),$safetyCode);if($safetyCode!==0){fwrite(STDERR,"Restore cancelled because safety backup failed.\n");exit(1);}if(!function_exists('proc_open')){fwrite(STDERR,"proc_open is required.\n");exit(1);} $mysqlBinary=mysql_client_binary();$defaultsFile=tempnam(sys_get_temp_dir(),'pos-db-');if($defaultsFile===false)throw new RuntimeException('Could not create temporary credential file.');$escaped=addcslashes(DB_PASS,"\\\"");file_put_contents($defaultsFile,"[client]\nhost=".DB_HOST."\nport=".DB_PORT."\nuser=".DB_USER."\npassword=\"".$escaped."\"\ndefault-character-set=utf8mb4\n",LOCK_EX);@chmod($defaultsFile,0600);
$command=[$mysqlBinary,'--defaults-extra-file='.$defaultsFile,DB_NAME];$desc=[0=>['file',$resolved,'rb'],1=>['pipe','w'],2=>['pipe','w']];$process=proc_open($command,$desc,$pipes,__DIR__);if(!is_resource($process)){@unlink($defaultsFile);throw new RuntimeException('Could not start restore.');}$output=stream_get_contents($pipes[1]);$errors=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$code=proc_close($process);@unlink($defaultsFile);if($code!==0){fwrite(STDERR,'Restore failed: '.trim($errors).PHP_EOL);exit(1);}echo trim($output).PHP_EOL;echo 'Database restore complete. Upload snapshot was verified but not automatically overwritten: '.$assetDir.PHP_EOL;
